#ifndef _DA_CONFIG_H
#define _DA_CONFIG_H

#define SYSTEM_APP_VERSION	 0x01
#define FIRMWARE_SIGNATURE   0x04

#define FIRMWARE_BANK1_ADDR  			   (0x0004C000UL)
#define FIRMWARE_BANK1_END 			   	   (0x00072000UL)
#define ADDR_BOOTLOADER_START 			   (0x000E4000UL)
#define BANK1_REGION_SIZE                  ((FIRMWARE_BANK1_END) - (FIRMWARE_BANK1_ADDR))
#define BANK1_BLOCK_MAXSIZE                BANK1_REGION_SIZE/CODE_PAGE_SIZE


#endif
